// JavaScript Document
// Nazir Shuqair
// VFW 1308
// 29 Aug 2013
// Project 4

var json = {
	"conference1": {
		"date": ["Date: ", "2013-08-21"], 		
		"nameM": ["Name of the meeting: ", "COS Meeting"], 	
		"poc": ["Contact Number: ", "702-221-2222"],		
		"roomN": ["Room Number: ", "1-307"], 		
		"meetingT": ["Meeting Time: ", "15:13"], 	
		"checkb": ["Is a VIP Present: ", "vip"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "32435#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "no"], 
		"notes": ["Notes", "Nothing here"]		
	},
	"conference2": {
		"date": ["Date: ", "2014-05-25"], 		
		"nameM": ["Name of the meeting: ", "M6 Meeting"], 	
		"poc": ["Contact Number: ", "702-221-3333"],		
		"roomN": ["Room Number: ", "1-439"], 		
		"meetingT": ["Meeting Time: ", "19:43"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Video"], 	
		"code": ["Call code: ", "55555#"], 		
		"length": ["Length of Meeting: ", "1hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Something here"]		
	},
	"conference3": {
		"date": ["Date: ", "2013-11-25"], 		
		"nameM": ["Name of the meeting: ", "Navy"], 	
		"poc": ["Contact Number: ", "702-222-3333"],		
		"roomN": ["Room Number: ", "1-232"], 		
		"meetingT": ["Meeting Time: ", "21:00"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Audio"], 	
		"code": ["Call code: ", "46545#"], 		
		"length": ["Length of Meeting: ", "3hr"], 	
		"userR": ["Did the user respond: ", "no"], 
		"notes": ["Notes", "nothing to report"]		
	},
	"conference4": {
		"date": ["Date: ", "2013-12-15"], 		
		"nameM": ["Name of the meeting: ", "COS reocurring"], 	
		"poc": ["Contact Number: ", "702-221-4353"],		
		"roomN": ["Room Number: ", "2-443"], 		
		"meetingT": ["Meeting Time: ", "06:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "56322#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "User needs special software"]		
	},
	"conference5": {
		"date": ["Date: ", "2013-12-24"], 		
		"nameM": ["Name of the meeting: ", "Holiday party"], 	
		"poc": ["Contact Number: ", "702-221-5664"],		
		"roomN": ["Room Number: ", "2-303"], 		
		"meetingT": ["Meeting Time: ", "09:30"], 	
		"checkb": ["Is a VIP Present: ", "vip"], 	
		"bridges": ["Bridge: ", "USAMTIC Video"], 	
		"code": ["Call code: ", "76544#"], 		
		"length": ["Length of Meeting: ", "4hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Nothing"]		
	},
	"conference6": {
		"date": ["Date: ", "2014-01-15"], 		
		"nameM": ["Name of the meeting: ", "Planning"], 	
		"poc": ["Contact Number: ", "702-221-4534"],		
		"roomN": ["Room Number: ", "2-544"], 		
		"meetingT": ["Meeting Time: ", "11:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "54226#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Needs HDMI cable"]		
	},
	"conference7": {
		"date": ["Date: ", "2013-01-25"], 		
		"nameM": ["Name of the meeting: ", "MAC"], 	
		"poc": ["Contact Number: ", "702-221-7686"],		
		"roomN": ["Room Number: ", "2-443"], 		
		"meetingT": ["Meeting Time: ", "13:30"], 	
		"checkb": ["Is a VIP Present: ", "vip"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "32332#"], 		
		"length": ["Length of Meeting: ", "1hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Nothing"]		
	},
	"conference8": {
		"date": ["Date: ", "2014-02-14"], 		
		"nameM": ["Name of the meeting: ", "Tech training"], 	
		"poc": ["Contact Number: ", "702-221-2132"],		
		"roomN": ["Room Number: ", "2-557"], 		
		"meetingT": ["Meeting Time: ", "10:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Video"], 	
		"code": ["Call code: ", "86554#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Monitor setup"]		
	},
	"conference9": {
		"date": ["Date: ", "2014-03-02"], 		
		"nameM": ["Name of the meeting: ", "Design"], 	
		"poc": ["Contact Number: ", "702-221-8786"],		
		"roomN": ["Room Number: ", "2-111"], 		
		"meetingT": ["Meeting Time: ", "15:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "USAMTIC audio"], 	
		"code": ["Call code: ", "68975#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Nothing"]		
	},
	"conference10": {
		"date": ["Date: ", "2014-03-02"], 		
		"nameM": ["Name of the meeting: ", "SharePoint"], 	
		"poc": ["Contact Number: ", "702-221-5543"],		
		"roomN": ["Room Number: ", "2-423"], 		
		"meetingT": ["Meeting Time: ", "14:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "USAMTIC audio"], 	
		"code": ["Call code: ", "32235#"], 		
		"length": ["Length of Meeting: ", "1hr"], 	
		"userR": ["Did the user respond: ", "no"], 
		"notes": ["Notes", "Nothing"]		
	},
	"conference11": {
		"date": ["Date: ", "2014-03-05"], 		
		"nameM": ["Name of the meeting: ", "Birthday party"], 	
		"poc": ["Contact Number: ", "702-221-5664"],		
		"roomN": ["Room Number: ", "2-303"], 		
		"meetingT": ["Meeting Time: ", "09:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Video"], 	
		"code": ["Call code: ", "76544#"], 		
		"length": ["Length of Meeting: ", "1hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Nothing"]		
	},
	"conference12": {
		"date": ["Date: ", "2014-03-25"], 		
		"nameM": ["Name of the meeting: ", "Tech training"], 	
		"poc": ["Contact Number: ", "702-221-2132"],		
		"roomN": ["Room Number: ", "2-557"], 		
		"meetingT": ["Meeting Time: ", "10:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Video"], 	
		"code": ["Call code: ", "86554#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Monitor setup"]		
	},
	"conference13": {
		"date": ["Date: ", "2014-04-01"], 		
		"nameM": ["Name of the meeting: ", "COS Meeting"], 	
		"poc": ["Contact Number: ", "702-221-2222"],		
		"roomN": ["Room Number: ", "1-307"], 		
		"meetingT": ["Meeting Time: ", "15:13"], 	
		"checkb": ["Is a VIP Present: ", "vip"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "32435#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "no"], 
		"notes": ["Notes", "Nothing here"]		
	},
	"conference14": {
		"date": ["Date: ", "2014-04-04"], 		
		"nameM": ["Name of the meeting: ", "M6 Meeting"], 	
		"poc": ["Contact Number: ", "702-221-3333"],		
		"roomN": ["Room Number: ", "1-439"], 		
		"meetingT": ["Meeting Time: ", "19:43"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Video"], 	
		"code": ["Call code: ", "55555#"], 		
		"length": ["Length of Meeting: ", "1hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Something here"]		
	},
	"conference15": {
		"date": ["Date: ", "2014-04-13"], 		
		"nameM": ["Name of the meeting: ", "Navy Pride"], 	
		"poc": ["Contact Number: ", "702-222-3333"],		
		"roomN": ["Room Number: ", "1-232"], 		
		"meetingT": ["Meeting Time: ", "13:00"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Audio"], 	
		"code": ["Call code: ", "46545#"], 		
		"length": ["Length of Meeting: ", "3hr"], 	
		"userR": ["Did the user respond: ", "no"], 
		"notes": ["Notes", "nothing to report"]		
	},
	"conference16": {
		"date": ["Date: ", "2014-04-15"], 		
		"nameM": ["Name of the meeting: ", "COS reocurring"], 	
		"poc": ["Contact Number: ", "702-221-4353"],		
		"roomN": ["Room Number: ", "2-443"], 		
		"meetingT": ["Meeting Time: ", "06:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "56322#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "User needs special software"]		
	},
	"conference17": {
		"date": ["Date: ", "2014-04-29"], 		
		"nameM": ["Name of the meeting: ", "Planning"], 	
		"poc": ["Contact Number: ", "702-221-4534"],		
		"roomN": ["Room Number: ", "2-544"], 		
		"meetingT": ["Meeting Time: ", "11:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "54226#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Needs HDMI cable"]		
	},
	"conference18": {
		"date": ["Date: ", "2014-04-25"], 		
		"nameM": ["Name of the meeting: ", "MDM"], 	
		"poc": ["Contact Number: ", "702-221-4653"],		
		"roomN": ["Room Number: ", "2-332"], 		
		"meetingT": ["Meeting Time: ", "13:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Video"], 	
		"code": ["Call code: ", "54346#"], 		
		"length": ["Length of Meeting: ", "3hr"], 	
		"userR": ["Did the user respond: ", "no"], 
		"notes": ["Notes", "Nothing"]		
	},
	"conference19": {
		"date": ["Date: ", "2014-04-28"], 		
		"nameM": ["Name of the meeting: ", "Tech training"], 	
		"poc": ["Contact Number: ", "702-221-2132"],		
		"roomN": ["Room Number: ", "2-557"], 		
		"meetingT": ["Meeting Time: ", "10:30"], 	
		"checkb": ["Is a VIP Present: ", "no"], 	
		"bridges": ["Bridge: ", "TMS Video"], 	
		"code": ["Call code: ", "86554#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "Monitor setup"]		
	},
	"conference20": {
		"date": ["Date: ", "2014-05-01"], 		
		"nameM": ["Name of the meeting: ", "COS reocurring"], 	
		"poc": ["Contact Number: ", "702-221-4353"],		
		"roomN": ["Room Number: ", "2-443"], 		
		"meetingT": ["Meeting Time: ", "06:30"], 	
		"checkb": ["Is a VIP Present: ", "vip"], 	
		"bridges": ["Bridge: ", "USAMTIC Audio"], 	
		"code": ["Call code: ", "56322#"], 		
		"length": ["Length of Meeting: ", "2hr"], 	
		"userR": ["Did the user respond: ", "yes"], 
		"notes": ["Notes", "User needs special software"]		
	},
}